services:
  - type: web
    name: tongue-ai-app
    env: docker
    plan: free
    branch: main
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: PORT
        value: 8080
